-- ============================================================================
-- DULCE FE - SCRIPT DE INICIALIZACIÓN COMPLETA DE BASE DE DATOS (DEV / PROD)
-- Consolida esquema, extensiones, tablas, funciones, triggers, RLS y storage
-- ============================================================================

-- 1. TABLAS PRINCIPALES

-- Categorías de Productos
CREATE TABLE IF NOT EXISTS public.categories (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    icon TEXT DEFAULT 'lucide:sparkles' NOT NULL,
    sort_order INT DEFAULT 0 NOT NULL,
    is_active BOOLEAN DEFAULT true NOT NULL,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Productos Comerciales
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    price NUMERIC(10,2),
    stock INTEGER DEFAULT 0,
    image_url TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

-- Materias Primas / Insumos de Almacén
CREATE TABLE IF NOT EXISTS public.raw_materials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    unit TEXT,
    stock NUMERIC,
    purchase_price NUMERIC,
    purchase_quantity NUMERIC,
    type VARCHAR(20) NOT NULL DEFAULT 'ingredient',
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Constraint nombrada para coincidir con producción (migración 20260924170000)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'raw_materials_type_check'
  ) THEN
    ALTER TABLE public.raw_materials
    ADD CONSTRAINT raw_materials_type_check 
    CHECK (type IN ('ingredient', 'packaging'));
  END IF;
END $$;
CREATE INDEX IF NOT EXISTS idx_raw_materials_type ON public.raw_materials(type);

-- Recetas Simples de Productos (Escandallo directo legacy)
CREATE TABLE IF NOT EXISTS public.recipe_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE NOT NULL,
    raw_material_id BIGINT REFERENCES public.raw_materials(id) ON DELETE RESTRICT NOT NULL,
    quantity_used NUMERIC,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Perfiles de Usuario (Extensión de auth.users)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    full_name TEXT,
    phone TEXT,
    birth_date DATE,
    points INTEGER DEFAULT 0,
    is_admin BOOLEAN DEFAULT false,
    email TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Direcciones de Envío
CREATE TABLE IF NOT EXISTS public.addresses (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    profile_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    label TEXT NOT NULL,
    address_line TEXT NOT NULL,
    is_default BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Pedidos (Orders)
CREATE TABLE IF NOT EXISTS public.orders (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    profile_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    customer_name TEXT,
    customer_phone TEXT,
    address TEXT,
    total_amount NUMERIC(12,2) NOT NULL,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'ready', 'completed', 'cancelled')),
    delivery_date TEXT,
    delivery_time TEXT,
    notes TEXT,
    inventory_processed BOOLEAN NOT NULL DEFAULT false,
    points_awarded BOOLEAN NOT NULL DEFAULT false,
    cancellation_reason TEXT DEFAULT NULL,
    tracking_token VARCHAR(64) UNIQUE,
    payment_method VARCHAR(20) DEFAULT 'cash' CHECK (payment_method IN ('cash', 'yape', 'plin', 'card')),
    payment_reference VARCHAR(100) DEFAULT NULL,
    payment_receipt_url TEXT DEFAULT NULL,
    payment_status VARCHAR(20) DEFAULT 'pending' CHECK (payment_status IN ('pending', 'verified', 'rejected')),
    payment_verified_at TIMESTAMPTZ DEFAULT NULL,
    payment_verified_by UUID REFERENCES public.profiles(id) DEFAULT NULL,
    cost_snapshot JSONB DEFAULT NULL,
    total_cost_cents INTEGER DEFAULT NULL,
    gross_margin_cents INTEGER DEFAULT NULL,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_orders_payment_status ON public.orders(payment_status);
CREATE INDEX IF NOT EXISTS idx_orders_payment_method ON public.orders(payment_method);
CREATE INDEX IF NOT EXISTS idx_orders_tracking_token ON public.orders(tracking_token);

-- Items de Pedido
CREATE TABLE IF NOT EXISTS public.order_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id UUID NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    price_at_time NUMERIC(12,2) NOT NULL CHECK (price_at_time >= 0),
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Carritos de Compra
CREATE TABLE IF NOT EXISTS public.carts (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id)
);

CREATE TABLE IF NOT EXISTS public.cart_items (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    cart_id UUID REFERENCES public.carts(id) ON DELETE CASCADE NOT NULL,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1 CHECK (quantity > 0),
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(cart_id, product_id)
);

-- Infraestructura de Idempotencia y Rate Limiting
CREATE TABLE IF NOT EXISTS public.checkout_idempotency_keys (
    operation TEXT NOT NULL,
    principal_scope TEXT NOT NULL,
    key TEXT NOT NULL,
    request_hash TEXT NOT NULL,
    order_id UUID REFERENCES public.orders(id) ON DELETE CASCADE,
    lifecycle TEXT NOT NULL CHECK (lifecycle IN ('processing', 'completed')),
    status_code INT NOT NULL DEFAULT 201,
    response_payload JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (operation, principal_scope, key)
);

CREATE INDEX IF NOT EXISTS checkout_idempotency_keys_expires_at_idx
    ON public.checkout_idempotency_keys (expires_at);

CREATE TABLE IF NOT EXISTS public.checkout_rate_windows (
    ip INET NOT NULL,
    window_start TIMESTAMPTZ NOT NULL,
    hit_count INT NOT NULL DEFAULT 1,
    PRIMARY KEY (ip, window_start)
);

-- Auditoría Inmutable
CREATE TABLE IF NOT EXISTS public.audit_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    actor_id UUID,
    action TEXT NOT NULL CHECK (action IN (
        'checkout.create', 'order.create_admin', 'order.status', 
        'product.write', 'material.write', 'recipe.write', 
        'upload.write', 'stock.adjust', 'payment.verify', 
        'payment.verified', 'payment.rejected'
    )),
    entity TEXT NOT NULL,
    entity_id TEXT,
    result TEXT NOT NULL CHECK (result IN ('ok', 'error')),
    request_id TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Libro de Movimientos de Inventario
CREATE TABLE IF NOT EXISTS public.inventory_movements (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    raw_material_id BIGINT NOT NULL REFERENCES public.raw_materials(id) ON DELETE RESTRICT,
    order_id UUID REFERENCES public.orders(id) ON DELETE SET NULL,
    type TEXT NOT NULL CHECK (type IN ('order_consumption', 'manual_adjustment', 'cancellation_reversal', 'waste_declaration')),
    quantity_delta NUMERIC(14,4) NOT NULL,
    stock_before NUMERIC(14,4) NOT NULL,
    stock_after NUMERIC(14,4) NOT NULL,
    reason TEXT,
    actor_id UUID,
    request_id TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS inventory_movements_one_consumption_per_order_material
    ON public.inventory_movements (order_id, raw_material_id)
    WHERE type = 'order_consumption';

-- 2. MOTOR DE TANDAS, RENDIMIENTOS Y EMPAQUES (FASE 7)

CREATE TABLE IF NOT EXISTS public.base_recipes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    description TEXT,
    labor_cost NUMERIC(10, 2) DEFAULT 0.00 NOT NULL CHECK (labor_cost >= 0),
    utilities_cost NUMERIC(10, 2) DEFAULT 0.00 NOT NULL CHECK (utilities_cost >= 0),
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.base_recipe_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    base_recipe_id BIGINT REFERENCES public.base_recipes(id) ON DELETE CASCADE NOT NULL,
    raw_material_id BIGINT REFERENCES public.raw_materials(id) ON DELETE RESTRICT NOT NULL,
    quantity_used NUMERIC(10, 4) NOT NULL CHECK (quantity_used > 0),
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.recipe_yields (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    base_recipe_id BIGINT REFERENCES public.base_recipes(id) ON DELETE CASCADE NOT NULL,
    size_name VARCHAR(100) NOT NULL,
    yield_units INT NOT NULL CHECK (yield_units > 0),
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.product_recipe_mappings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE NOT NULL,
    recipe_yield_id BIGINT REFERENCES public.recipe_yields(id) ON DELETE RESTRICT NOT NULL,
    units_contained INT NOT NULL CHECK (units_contained > 0),
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.product_packaging_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE NOT NULL,
    raw_material_id BIGINT REFERENCES public.raw_materials(id) ON DELETE RESTRICT NOT NULL,
    quantity_used NUMERIC(10, 4) NOT NULL CHECK (quantity_used > 0),
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.piece_waste_logs (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    recipe_yield_id BIGINT REFERENCES public.recipe_yields(id) ON DELETE RESTRICT NOT NULL,
    pieces_count INT NOT NULL CHECK (pieces_count > 0),
    reason VARCHAR(50) NOT NULL CHECK (reason IN ('personal_consumption', 'gift', 'spoilage', 'direct_sale')),
    notes TEXT,
    profile_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_base_recipe_items_recipe ON public.base_recipe_items(base_recipe_id);
CREATE INDEX IF NOT EXISTS idx_recipe_yields_recipe ON public.recipe_yields(base_recipe_id);
CREATE INDEX IF NOT EXISTS idx_product_recipe_mappings_product ON public.product_recipe_mappings(product_id);
CREATE INDEX IF NOT EXISTS idx_product_packaging_items_product ON public.product_packaging_items(product_id);
CREATE INDEX IF NOT EXISTS idx_piece_waste_logs_yield ON public.piece_waste_logs(recipe_yield_id);

-- 3. FUNCIONES DE SEGURIDAD, NEGOCIO Y PROCEDIMIENTOS ALMACENADOS

-- Función base para verificar rol admin
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN
LANGUAGE sql
SECURITY DEFINER
SET search_path = public, pg_temp
STABLE
AS $$
  SELECT COALESCE(
    (SELECT is_admin FROM public.profiles WHERE id = auth.uid()),
    false
  );
$$;

-- Función para actualizar timestamp del carrito
CREATE OR REPLACE FUNCTION public.update_cart_timestamp()
RETURNS TRIGGER 
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
    -- NEW es NULL en DELETE, OLD es NULL en INSERT
    IF TG_OP = 'DELETE' THEN
        UPDATE public.carts
        SET updated_at = timezone('utc'::text, now())
        WHERE id = OLD.cart_id;
        RETURN NULL;
    END IF;
    UPDATE public.carts
    SET updated_at = timezone('utc'::text, now())
    WHERE id = NEW.cart_id;
    RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS update_cart_timestamp_trigger ON public.cart_items;
CREATE TRIGGER update_cart_timestamp_trigger
AFTER INSERT OR UPDATE OR DELETE ON public.cart_items
FOR EACH ROW EXECUTE FUNCTION public.update_cart_timestamp();

-- Trigger para perfiles de nuevos usuarios auth
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, email, phone, is_admin)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'full_name', ''),
    NEW.email,
    NEW.raw_user_meta_data->>'phone',
    false
  )
  ON CONFLICT (id) DO UPDATE SET
    full_name = COALESCE(EXCLUDED.full_name, profiles.full_name),
    email = COALESCE(EXCLUDED.email, profiles.email),
    phone = COALESCE(EXCLUDED.phone, profiles.phone);
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Función para procesar inventario al confirmar pedido
CREATE OR REPLACE FUNCTION public.process_order_inventory(order_uuid UUID)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    item RECORD;
    recipe_row RECORD;
    total_needed DECIMAL;
BEGIN
    FOR item IN 
        SELECT product_id, quantity 
        FROM public.order_items 
        WHERE order_id = order_uuid
    LOOP
        FOR recipe_row IN 
            SELECT raw_material_id, quantity_used 
            FROM public.recipe_items 
            WHERE product_id = item.product_id
        LOOP
            total_needed := recipe_row.quantity_used * item.quantity;
            
            UPDATE public.raw_materials
            SET stock = stock - total_needed
            WHERE id = recipe_row.raw_material_id;
        END LOOP;
    END LOOP;
END;
$$;

-- Función de reversión atómica de inventario (cancelación o merma)
CREATE OR REPLACE FUNCTION public.revert_order_inventory(
  p_order_id UUID,
  p_reason TEXT,
  p_restore_stock BOOLEAN,
  p_actor_id UUID DEFAULT NULL,
  p_request_id TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_order RECORD;
  v_movement RECORD;
  v_mat RECORD;
  v_stock_before NUMERIC;
  v_stock_after NUMERIC;
  v_restored_count INT := 0;
  v_consumed_qty NUMERIC;
BEGIN
  SELECT * INTO v_order FROM orders WHERE id = p_order_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'ORDER_NOT_FOUND';
  END IF;

  FOR v_movement IN 
    SELECT * FROM inventory_movements 
    WHERE order_id = p_order_id AND type = 'order_consumption'
  LOOP
    v_consumed_qty := ABS(v_movement.quantity_delta);

    SELECT * INTO v_mat FROM raw_materials WHERE id = v_movement.raw_material_id FOR UPDATE;
    IF FOUND THEN
      v_stock_before := v_mat.stock;

      IF p_restore_stock THEN
        v_stock_after := v_stock_before + v_consumed_qty;
        UPDATE raw_materials SET stock = v_stock_after WHERE id = v_mat.id;

        INSERT INTO inventory_movements (
          raw_material_id, order_id, type, quantity_delta,
          stock_before, stock_after, reason, actor_id, request_id
        ) VALUES (
          v_mat.id, p_order_id, 'cancellation_reversal', v_consumed_qty,
          v_stock_before, v_stock_after, p_reason, p_actor_id, p_request_id
        );
      ELSE
        INSERT INTO inventory_movements (
          raw_material_id, order_id, type, quantity_delta,
          stock_before, stock_after, reason, actor_id, request_id
        ) VALUES (
          v_mat.id, p_order_id, 'waste_declaration', 0,
          v_stock_before, v_stock_before, p_reason, p_actor_id, p_request_id
        );
      END IF;

      v_restored_count := v_restored_count + 1;
    END IF;
  END LOOP;

  UPDATE orders 
  SET 
    status = 'cancelled',
    cancellation_reason = p_reason
  WHERE id = p_order_id;

  RETURN jsonb_build_object(
    'order_id', p_order_id,
    'status', 'cancelled',
    'restored_items_count', v_restored_count,
    'stock_restored', p_restore_stock
  );
END;
$$;

-- Función de Puntos de Fidelidad
CREATE OR REPLACE FUNCTION public.award_loyalty_points(order_uuid UUID)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_order RECORD;
    v_points_to_award INTEGER;
BEGIN
    SELECT id, profile_id, total_amount, points_awarded 
    INTO v_order
    FROM public.orders 
    WHERE id = order_uuid;

    IF v_order.id IS NULL OR v_order.points_awarded = TRUE THEN
        RETURN;
    END IF;

    v_points_to_award := FLOOR(v_order.total_amount);

    IF v_points_to_award > 0 AND v_order.profile_id IS NOT NULL THEN
        UPDATE public.profiles
        SET points = COALESCE(points, 0) + v_points_to_award,
            updated_at = NOW()
        WHERE id = v_order.profile_id;

        UPDATE public.orders
        SET points_awarded = TRUE
        WHERE id = order_uuid;
    END IF;
END;
$$;

-- Revocación de RPCs sensibles a roles de navegador
REVOKE EXECUTE ON FUNCTION public.process_order_inventory(uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.award_loyalty_points(uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.process_order_inventory(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.award_loyalty_points(uuid) TO service_role;

-- 5. HABILITACIÓN DE ROW LEVEL SECURITY (RLS)

ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.raw_materials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recipe_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.addresses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.carts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cart_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.checkout_idempotency_keys ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.checkout_rate_windows ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_movements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.base_recipes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.base_recipe_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recipe_yields ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_recipe_mappings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_packaging_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.piece_waste_logs ENABLE ROW LEVEL SECURITY;

-- 6. POLÍTICAS RLS FORMALES

-- Categories
DROP POLICY IF EXISTS "Public read active categories" ON public.categories;
CREATE POLICY "Public read active categories" ON public.categories FOR SELECT USING (is_active = true);
DROP POLICY IF EXISTS "Admin manage categories" ON public.categories;
CREATE POLICY "Admin manage categories" ON public.categories FOR ALL USING (public.is_admin());

-- Products
DROP POLICY IF EXISTS "products_select_public" ON public.products;
CREATE POLICY "products_select_public" ON public.products FOR SELECT USING (true);
DROP POLICY IF EXISTS "products_insert_admin" ON public.products;
CREATE POLICY "products_insert_admin" ON public.products FOR INSERT WITH CHECK (public.is_admin() = true);
DROP POLICY IF EXISTS "products_update_admin" ON public.products;
CREATE POLICY "products_update_admin" ON public.products FOR UPDATE USING (public.is_admin() = true) WITH CHECK (public.is_admin() = true);
DROP POLICY IF EXISTS "products_delete_admin" ON public.products;
CREATE POLICY "products_delete_admin" ON public.products FOR DELETE USING (public.is_admin() = true);

-- Raw Materials & Recipes
DROP POLICY IF EXISTS "raw_materials_all_admin" ON public.raw_materials;
CREATE POLICY "raw_materials_all_admin" ON public.raw_materials FOR ALL USING (public.is_admin() = true) WITH CHECK (public.is_admin() = true);
DROP POLICY IF EXISTS "recipe_items_all_admin" ON public.recipe_items;
CREATE POLICY "recipe_items_all_admin" ON public.recipe_items FOR ALL USING (public.is_admin() = true) WITH CHECK (public.is_admin() = true);

-- Profiles
DROP POLICY IF EXISTS "profiles_select_self_or_admin" ON public.profiles;
CREATE POLICY "profiles_select_self_or_admin" ON public.profiles FOR SELECT USING (auth.uid() = id OR public.is_admin() = true);
DROP POLICY IF EXISTS "profiles_update_self_or_admin" ON public.profiles;
CREATE POLICY "profiles_update_self_or_admin" ON public.profiles FOR UPDATE USING (auth.uid() = id OR public.is_admin() = true)
WITH CHECK (
  (auth.uid() = id AND is_admin IS NOT DISTINCT FROM (SELECT p.is_admin FROM public.profiles p WHERE p.id = auth.uid()))
  OR public.is_admin() = true
);

-- Addresses
DROP POLICY IF EXISTS "addresses_all_owner_or_admin" ON public.addresses;
CREATE POLICY "addresses_all_owner_or_admin" ON public.addresses FOR ALL USING (auth.uid() = profile_id OR public.is_admin() = true) WITH CHECK (auth.uid() = profile_id OR public.is_admin() = true);

-- Orders & Order Items
DROP POLICY IF EXISTS "orders_select_owner_or_admin" ON public.orders;
CREATE POLICY "orders_select_owner_or_admin" ON public.orders FOR SELECT USING (auth.uid() = profile_id OR public.is_admin() = true);
DROP POLICY IF EXISTS "orders_insert_admin_only" ON public.orders;
CREATE POLICY "orders_insert_admin_only" ON public.orders FOR INSERT WITH CHECK (public.is_admin() = true);
DROP POLICY IF EXISTS "orders_update_admin" ON public.orders;
CREATE POLICY "orders_update_admin" ON public.orders FOR UPDATE USING (public.is_admin() = true) WITH CHECK (public.is_admin() = true);

DROP POLICY IF EXISTS "order_items_select_owner_or_admin" ON public.order_items;
CREATE POLICY "order_items_select_owner_or_admin" ON public.order_items FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM public.orders o
    WHERE o.id = order_items.order_id
    AND (o.profile_id = auth.uid() OR public.is_admin() = true)
  )
);
DROP POLICY IF EXISTS "order_items_insert_admin_only" ON public.order_items;
CREATE POLICY "order_items_insert_admin_only" ON public.order_items FOR INSERT WITH CHECK (public.is_admin() = true);

-- Carts
DROP POLICY IF EXISTS "Usuarios pueden ver su propio carrito" ON public.carts;
CREATE POLICY "Usuarios pueden ver su propio carrito" ON public.carts FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Usuarios pueden crear su propio carrito" ON public.carts;
CREATE POLICY "Usuarios pueden crear su propio carrito" ON public.carts FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Usuarios pueden actualizar su propio carrito" ON public.carts;
CREATE POLICY "Usuarios pueden actualizar su propio carrito" ON public.carts FOR UPDATE USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Usuarios pueden eliminar su propio carrito" ON public.carts;
CREATE POLICY "Usuarios pueden eliminar su propio carrito" ON public.carts FOR DELETE USING (auth.uid() = user_id);

-- Cart Items
DROP POLICY IF EXISTS "Usuarios pueden ver los items de su carrito" ON public.cart_items;
CREATE POLICY "Usuarios pueden ver los items de su carrito" ON public.cart_items FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.carts WHERE carts.id = cart_items.cart_id AND carts.user_id = auth.uid())
);
DROP POLICY IF EXISTS "Usuarios pueden agregar items a su carrito" ON public.cart_items;
CREATE POLICY "Usuarios pueden agregar items a su carrito" ON public.cart_items FOR INSERT WITH CHECK (
  EXISTS (SELECT 1 FROM public.carts WHERE carts.id = cart_items.cart_id AND carts.user_id = auth.uid())
);
DROP POLICY IF EXISTS "Usuarios pueden actualizar items de su carrito" ON public.cart_items;
CREATE POLICY "Usuarios pueden actualizar items de su carrito" ON public.cart_items FOR UPDATE USING (
  EXISTS (SELECT 1 FROM public.carts WHERE carts.id = cart_items.cart_id AND carts.user_id = auth.uid())
);
DROP POLICY IF EXISTS "Usuarios pueden eliminar items de su carrito" ON public.cart_items;
CREATE POLICY "Usuarios pueden eliminar items de su carrito" ON public.cart_items FOR DELETE USING (
  EXISTS (SELECT 1 FROM public.carts WHERE carts.id = cart_items.cart_id AND carts.user_id = auth.uid())
);

-- Batch Recipes (Fase 7)
DROP POLICY IF EXISTS "Admin manage base_recipes" ON public.base_recipes;
CREATE POLICY "Admin manage base_recipes" ON public.base_recipes FOR ALL USING (public.is_admin());
DROP POLICY IF EXISTS "Admin manage base_recipe_items" ON public.base_recipe_items;
CREATE POLICY "Admin manage base_recipe_items" ON public.base_recipe_items FOR ALL USING (public.is_admin());
DROP POLICY IF EXISTS "Admin manage recipe_yields" ON public.recipe_yields;
CREATE POLICY "Admin manage recipe_yields" ON public.recipe_yields FOR ALL USING (public.is_admin());
DROP POLICY IF EXISTS "Admin manage product_recipe_mappings" ON public.product_recipe_mappings;
CREATE POLICY "Admin manage product_recipe_mappings" ON public.product_recipe_mappings FOR ALL USING (public.is_admin());
DROP POLICY IF EXISTS "Admin manage product_packaging_items" ON public.product_packaging_items;
CREATE POLICY "Admin manage product_packaging_items" ON public.product_packaging_items FOR ALL USING (public.is_admin());
DROP POLICY IF EXISTS "Admin manage piece_waste_logs" ON public.piece_waste_logs;
CREATE POLICY "Admin manage piece_waste_logs" ON public.piece_waste_logs FOR ALL USING (public.is_admin());

-- 7. STORAGE BUCKET Y POLÍTICAS (payment-receipts)

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('payment-receipts', 'payment-receipts', true, 2097152, ARRAY['image/jpeg', 'image/png', 'image/webp'])
ON CONFLICT (id) DO UPDATE SET public = true;

DROP POLICY IF EXISTS "Public Read Payment Receipts" ON storage.objects;
CREATE POLICY "Public Read Payment Receipts"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'payment-receipts');

DROP POLICY IF EXISTS "Public Upload Payment Receipts" ON storage.objects;
CREATE POLICY "Public Upload Payment Receipts"
  ON storage.objects FOR INSERT
  WITH CHECK (bucket_id = 'payment-receipts');

DROP POLICY IF EXISTS "Service Role Full Access Payment Receipts" ON storage.objects;
CREATE POLICY "Service Role Full Access Payment Receipts"
  ON storage.objects FOR ALL
  USING (bucket_id = 'payment-receipts')
  WITH CHECK (bucket_id = 'payment-receipts');

-- 8. SEED DATA DE EMPAQUES INICIALES (migración 20260924170000)

INSERT INTO public.raw_materials (name, unit, purchase_price, purchase_quantity, stock, type)
SELECT 'Caja Torta / Pastel 25x25cm', 'und', 25.00, 10, 10, 'packaging'
WHERE NOT EXISTS (SELECT 1 FROM public.raw_materials WHERE type = 'packaging');

INSERT INTO public.raw_materials (name, unit, purchase_price, purchase_quantity, stock, type)
SELECT 'Bolsa Kraft Dulce Fe (Mediana)', 'und', 15.00, 25, 25, 'packaging'
WHERE NOT EXISTS (SELECT 1 FROM public.raw_materials WHERE name = 'Bolsa Kraft Dulce Fe (Mediana)');

INSERT INTO public.raw_materials (name, unit, purchase_price, purchase_quantity, stock, type)
SELECT 'Domo Transparente Individual', 'und', 18.00, 20, 20, 'packaging'
WHERE NOT EXISTS (SELECT 1 FROM public.raw_materials WHERE name = 'Domo Transparente Individual');
