-- Migración: Motor de Tandas (Batch Recipes), Rendimientos (Yield) y Porcionamiento de Productos
-- SSOT: docs/01 - Estrategia & Negocio/plan-tandas-porcionamiento-recetas.md

-- 1. Cabecera de Receta Base / Tanda (ej. Masa de Roles de Canela Clásica)
CREATE TABLE IF NOT EXISTS public.base_recipes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    description TEXT,
    labor_cost NUMERIC(10, 2) DEFAULT 0.00 NOT NULL CHECK (labor_cost >= 0),
    utilities_cost NUMERIC(10, 2) DEFAULT 0.00 NOT NULL CHECK (utilities_cost >= 0),
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Insumos Crudos de la Tanda (harina, mantequilla, levadura)
CREATE TABLE IF NOT EXISTS public.base_recipe_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    base_recipe_id BIGINT REFERENCES public.base_recipes(id) ON DELETE CASCADE NOT NULL,
    raw_material_id BIGINT REFERENCES public.raw_materials(id) ON DELETE RESTRICT NOT NULL,
    quantity_used NUMERIC(10, 4) NOT NULL CHECK (quantity_used > 0),
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Variantes de Rendimiento por Corte (Grande = 12u, Mediano = 18u, Mini = 24u)
CREATE TABLE IF NOT EXISTS public.recipe_yields (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    base_recipe_id BIGINT REFERENCES public.base_recipes(id) ON DELETE CASCADE NOT NULL,
    size_name VARCHAR(100) NOT NULL,
    yield_units INT NOT NULL CHECK (yield_units > 0),
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Asignación de Porciones a Productos Comerciales (ej. Caja 6 Roles Medianos)
CREATE TABLE IF NOT EXISTS public.product_recipe_mappings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE NOT NULL,
    recipe_yield_id BIGINT REFERENCES public.recipe_yields(id) ON DELETE RESTRICT NOT NULL,
    units_contained INT NOT NULL CHECK (units_contained > 0),
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Empaques Directos del Producto Comercial (caja de cartón, cinta, sticker)
CREATE TABLE IF NOT EXISTS public.product_packaging_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE NOT NULL,
    raw_material_id BIGINT REFERENCES public.raw_materials(id) ON DELETE RESTRICT NOT NULL,
    quantity_used NUMERIC(10, 4) NOT NULL CHECK (quantity_used > 0),
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Bitácora de Descargo Rápido de Piezas Sueltas (consumo personal, regalo, merma, venta externa)
CREATE TABLE IF NOT EXISTS public.piece_waste_logs (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    recipe_yield_id BIGINT REFERENCES public.recipe_yields(id) ON DELETE RESTRICT NOT NULL,
    pieces_count INT NOT NULL CHECK (pieces_count > 0),
    reason VARCHAR(50) NOT NULL CHECK (reason IN ('personal_consumption', 'gift', 'spoilage', 'direct_sale')),
    notes TEXT,
    profile_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Índices de Rendimiento para Búsqueda Rápida
CREATE INDEX IF NOT EXISTS idx_base_recipe_items_recipe ON public.base_recipe_items(base_recipe_id);
CREATE INDEX IF NOT EXISTS idx_recipe_yields_recipe ON public.recipe_yields(base_recipe_id);
CREATE INDEX IF NOT EXISTS idx_product_recipe_mappings_product ON public.product_recipe_mappings(product_id);
CREATE INDEX IF NOT EXISTS idx_product_packaging_items_product ON public.product_packaging_items(product_id);
CREATE INDEX IF NOT EXISTS idx_piece_waste_logs_yield ON public.piece_waste_logs(recipe_yield_id);

-- Habilitar Row Level Security (RLS) en las 6 tablas
ALTER TABLE public.base_recipes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.base_recipe_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recipe_yields ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_recipe_mappings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_packaging_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.piece_waste_logs ENABLE ROW LEVEL SECURITY;

-- Políticas RLS: Administradores tienen control total (is_admin() = true)
CREATE POLICY "Admin manage base_recipes" ON public.base_recipes
    FOR ALL
    USING (public.is_admin());

CREATE POLICY "Admin manage base_recipe_items" ON public.base_recipe_items
    FOR ALL
    USING (public.is_admin());

CREATE POLICY "Admin manage recipe_yields" ON public.recipe_yields
    FOR ALL
    USING (public.is_admin());

CREATE POLICY "Admin manage product_recipe_mappings" ON public.product_recipe_mappings
    FOR ALL
    USING (public.is_admin());

CREATE POLICY "Admin manage product_packaging_items" ON public.product_packaging_items
    FOR ALL
    USING (public.is_admin());

CREATE POLICY "Admin manage piece_waste_logs" ON public.piece_waste_logs
    FOR ALL
    USING (public.is_admin());

-- Comentarios Descriptivos de Gobernanza
COMMENT ON TABLE public.base_recipes IS 'Cabecera de recetas base o tandas de masa/preparación.';
COMMENT ON TABLE public.base_recipe_items IS 'Ingredientes crudos requeridos para la tanda completa.';
COMMENT ON TABLE public.recipe_yields IS 'Variantes de corte y rendimiento de unidades por tanda (Grande, Mediano, Mini).';
COMMENT ON TABLE public.product_recipe_mappings IS 'Asociación de productos comerciales con su rendimiento y cantidad de piezas.';
COMMENT ON TABLE public.product_packaging_items IS 'Insumos de empaque directo asignados a un producto comercial.';
COMMENT ON TABLE public.piece_waste_logs IS 'Bitácora auditable de descargo rápido de piezas sueltas.';
