-- ==============================================================================
-- BUNDLE DE MIGRACIONES PENDIENTES SUPABASE (PROYECTO: rklxfrwzuwjvnfcdhmei)
-- Incluye:
-- 1. 20260914000001_create_categories_table.sql
-- 2. 20260921000001_fix_profiles_email_and_signup_trigger.sql
-- 3. 20260922152500_create_batch_recipes_and_yields.sql
-- ==============================================================================

-- ------------------------------------------------------------------------------
-- 1. Categorías del Catálogo
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.categories (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    icon TEXT DEFAULT 'lucide:sparkles' NOT NULL,
    sort_order INT DEFAULT 0 NOT NULL,
    is_active BOOLEAN DEFAULT true NOT NULL,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public read active categories" ON public.categories;
CREATE POLICY "Public read active categories" ON public.categories
    FOR SELECT
    USING (is_active = true);

DROP POLICY IF EXISTS "Admin manage categories" ON public.categories;
CREATE POLICY "Admin manage categories" ON public.categories
    FOR ALL
    USING (public.is_admin());

COMMENT ON TABLE public.categories IS 'Categorías del catálogo de postres. Si no hay registros, la vitrina oculta las píldoras.';


-- ------------------------------------------------------------------------------
-- 2. Fix Email en Perfiles y Trigger de Signup
-- ------------------------------------------------------------------------------
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS email TEXT;

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, email, phone, is_admin)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'full_name', ''),
    NEW.email,
    NEW.raw_user_meta_data->>'phone',
    false
  )
  ON CONFLICT (id) DO UPDATE SET
    full_name = COALESCE(EXCLUDED.full_name, profiles.full_name),
    email = COALESCE(EXCLUDED.email, profiles.email),
    phone = COALESCE(EXCLUDED.phone, profiles.phone);
  RETURN NEW;
END;
$$;

DROP POLICY IF EXISTS "Public Upload Payment Receipts" ON storage.objects;
CREATE POLICY "Public Upload Payment Receipts"
  ON storage.objects FOR INSERT
  WITH CHECK (bucket_id = 'payment-receipts');

DROP POLICY IF EXISTS "Service Role Full Access Payment Receipts" ON storage.objects;
CREATE POLICY "Service Role Full Access Payment Receipts"
  ON storage.objects FOR ALL
  USING (bucket_id = 'payment-receipts')
  WITH CHECK (bucket_id = 'payment-receipts');


-- ------------------------------------------------------------------------------
-- 3. Motor de Tandas, Rendimientos y Porcionamiento
-- ------------------------------------------------------------------------------
-- 3.1 Cabecera de Receta Base / Tanda
CREATE TABLE IF NOT EXISTS public.base_recipes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    description TEXT,
    labor_cost NUMERIC(10, 2) DEFAULT 0.00 NOT NULL CHECK (labor_cost >= 0),
    utilities_cost NUMERIC(10, 2) DEFAULT 0.00 NOT NULL CHECK (utilities_cost >= 0),
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3.2 Insumos Crudos de la Tanda
CREATE TABLE IF NOT EXISTS public.base_recipe_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    base_recipe_id BIGINT REFERENCES public.base_recipes(id) ON DELETE CASCADE NOT NULL,
    raw_material_id BIGINT REFERENCES public.raw_materials(id) ON DELETE RESTRICT NOT NULL,
    quantity_used NUMERIC(10, 4) NOT NULL CHECK (quantity_used > 0),
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3.3 Variantes de Rendimiento por Corte
CREATE TABLE IF NOT EXISTS public.recipe_yields (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    base_recipe_id BIGINT REFERENCES public.base_recipes(id) ON DELETE CASCADE NOT NULL,
    size_name VARCHAR(100) NOT NULL,
    yield_units INT NOT NULL CHECK (yield_units > 0),
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3.4 Asignación de Porciones a Productos Comerciales
CREATE TABLE IF NOT EXISTS public.product_recipe_mappings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE NOT NULL,
    recipe_yield_id BIGINT REFERENCES public.recipe_yields(id) ON DELETE RESTRICT NOT NULL,
    units_contained INT NOT NULL CHECK (units_contained > 0),
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3.5 Empaques Directos del Producto Comercial
CREATE TABLE IF NOT EXISTS public.product_packaging_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE NOT NULL,
    raw_material_id BIGINT REFERENCES public.raw_materials(id) ON DELETE RESTRICT NOT NULL,
    quantity_used NUMERIC(10, 4) NOT NULL CHECK (quantity_used > 0),
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3.6 Bitácora de Descargo Rápido de Piezas Sueltas
CREATE TABLE IF NOT EXISTS public.piece_waste_logs (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    recipe_yield_id BIGINT REFERENCES public.recipe_yields(id) ON DELETE RESTRICT NOT NULL,
    pieces_count INT NOT NULL CHECK (pieces_count > 0),
    reason VARCHAR(50) NOT NULL CHECK (reason IN ('personal_consumption', 'gift', 'spoilage', 'direct_sale')),
    notes TEXT,
    profile_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Índices
CREATE INDEX IF NOT EXISTS idx_base_recipe_items_recipe ON public.base_recipe_items(base_recipe_id);
CREATE INDEX IF NOT EXISTS idx_recipe_yields_recipe ON public.recipe_yields(base_recipe_id);
CREATE INDEX IF NOT EXISTS idx_product_recipe_mappings_product ON public.product_recipe_mappings(product_id);
CREATE INDEX IF NOT EXISTS idx_product_packaging_items_product ON public.product_packaging_items(product_id);
CREATE INDEX IF NOT EXISTS idx_piece_waste_logs_yield ON public.piece_waste_logs(recipe_yield_id);

-- Habilitar RLS
ALTER TABLE public.base_recipes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.base_recipe_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recipe_yields ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_recipe_mappings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_packaging_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.piece_waste_logs ENABLE ROW LEVEL SECURITY;

-- Políticas RLS
DROP POLICY IF EXISTS "Admin manage base_recipes" ON public.base_recipes;
CREATE POLICY "Admin manage base_recipes" ON public.base_recipes FOR ALL USING (public.is_admin());

DROP POLICY IF EXISTS "Admin manage base_recipe_items" ON public.base_recipe_items;
CREATE POLICY "Admin manage base_recipe_items" ON public.base_recipe_items FOR ALL USING (public.is_admin());

DROP POLICY IF EXISTS "Admin manage recipe_yields" ON public.recipe_yields;
CREATE POLICY "Admin manage recipe_yields" ON public.recipe_yields FOR ALL USING (public.is_admin());

DROP POLICY IF EXISTS "Admin manage product_recipe_mappings" ON public.product_recipe_mappings;
CREATE POLICY "Admin manage product_recipe_mappings" ON public.product_recipe_mappings FOR ALL USING (public.is_admin());

DROP POLICY IF EXISTS "Admin manage product_packaging_items" ON public.product_packaging_items;
CREATE POLICY "Admin manage product_packaging_items" ON public.product_packaging_items FOR ALL USING (public.is_admin());

DROP POLICY IF EXISTS "Admin manage piece_waste_logs" ON public.piece_waste_logs;
CREATE POLICY "Admin manage piece_waste_logs" ON public.piece_waste_logs FOR ALL USING (public.is_admin());
